name: 'Cloudflare Accounts Token Creator'
description: 'Create Temporary Cloudflare Accounts Token'
author: 'Atolycs'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
   description: "Create Additional Accounts Token Key"
  account_id:
   description: "Cloudflare Account Id"

# Define your outputs here.
outputs:
  add_token:
    description: 'Additional Token'

runs:
  using: node20
  main: dist/index.js
